dist: bionic
addons:
  postgresql: '11'
  apt:
    sources:
      - ppa:chris-lea/redis-server
    packages:
      - postgresql-11-postgis-2.5
      - redis-tools
      - redis-server

services:
  - mysql
  - redis-server

before_script:
  - psql -U postgres -c "create extension postgis"
