dist: bionic

language: python

os:
  - linux

services:
  - docker

cache:
  pip: true
  directories:
    - $HOME/.cache/pip

addons:
  apt:
    packages:
      - python3-pip
      - python3-setuptools

before_script:
  # download openstreetmap-carto
  - git clone https://github.com/linuxluigi/openstreetmap-carto.git ../openstreetmap-carto
  # build docker images
  - sudo docker-compose -f local.yml build
  # download shape files
  - sudo docker-compose -f local.yml run --rm django /get-shapefiles.sh
  # generate style.xml
  - sudo docker-compose -f local.yml run --rm django python manage.py create_style_xml
  # start postgis server
  - sudo docker-compose -f local.yml up -d postgres
  # fill demo database
  - sudo docker-compose -f local.yml up test-database

install:
  # install docker-compose
  - pip3 install docker-compose wheel

script:
  - sudo docker-compose -f local.yml run django pytest
