dist: bionic

services:
  - postgresql
  - redis-server

addons:
  apt:
    sources:
      - ppa:chris-lea/redis-server
      - sourceline: 'deb http://apt.postgresql.org/pub/repos/apt/ bionic-pgdg main'
        key_url: 'https://www.postgresql.org/media/keys/ACCC4CF8.asc'
    packages:
    - redis-tools
    - redis-server
    - postgresql-client-11
    - postgresql-common
    - postgresql-11
    - postgresql-11-postgis-2.5
    - postgresql-11-pgrouting
    - netcat
    - postgresql-11-ogr-fdw

before_script:
  - sudo service postgresql restart
  - psql -c 'create database gis;' -U postgres
  - psql -c 'CREATE EXTENSION postgis;' -U postgres -d gis
  - psql -c 'CREATE EXTENSION postgis_topology;' -U postgres -d gis

env:
  global:
    - PGPORT=5432
    - PGHOST=localhost
    - PGDATABASE=gis
    - PGUSER=postgres

language: python

python:
  - "3.6"

script:
  - "pytest"
