dist: bionic

services:
  # https://docs.travis-ci.com/user/docker/
  - docker

cache:
  pip: true
  directories:
    - $HOME/.cache/pip

addons:
  apt:
    packages:
    - python3-pip

before_script:
  # download openstreetmap-carto
  - git clone https://github.com/linuxluigi/openstreetmap-carto.git ../openstreetmap-carto
  # build docker images
  - sudo docker-compose -f local.yml build
  # start postgis server
  - sudo docker-compose -f local.yml up -d postgres
  # fill demo database
  - sudo docker-compose -f local.yml up test-database

install:
  - pip3 install docker-compose

script:
  - sudo docker-compose -f local.yml run django pytest
