version: 1

update_configs:
  # ----------------------------------------------#
  #                    Python                     #
  # ----------------------------------------------#

  # traefik production
  - package_manager: "python"
    directory: "requirements"
    update_schedule: "daily"

  # ----------------------------------------------#
  #                  Dockerfiles                  #
  # ----------------------------------------------#

  # django local
  - package_manager: "docker"
    directory: "compose/local/django"
    update_schedule: "daily"

  # test-database local
  - package_manager: "docker"
    directory: "compose/local/test-database"
    update_schedule: "daily"

  # django production
  - package_manager: "docker"
    directory: "compose/production/django"
    update_schedule: "daily"

  # postgres production
  - package_manager: "docker"
    directory: "compose/production/postgres"
    update_schedule: "daily"

  # redis production
  - package_manager: "docker"
    directory: "compose/production/redis"
    update_schedule: "daily"

  # traefik production
  - package_manager: "docker"
    directory: "compose/production/traefik"
    update_schedule: "daily"
